import { BrandData, Product } from './types';

export interface StarterTemplate {
  id: string;
  category: string;
  emoji: string;
  name: string;
  description: string;
  industry: string;
  tagline: string;
  brandDescription: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  fontHeading: string;
  fontBody: string;
  brandVoice: string;
  toneKeywords: string[];
  channels: string[];
  products: Product[];
  chatbotPersona: string;
}

export const STARTER_TEMPLATES: StarterTemplate[] = [
  {
    id: 'restaurant',
    category: 'Restaurant/Food & Beverage',
    emoji: '🍕',
    name: 'Artisan Kitchen',
    description: 'A warm, inviting restaurant brand with farm-to-table focus',
    industry: 'Restaurant / Food & Beverage',
    tagline: 'From our kitchen to your heart',
    brandDescription: 'A farm-to-table restaurant celebrating local ingredients and seasonal flavors. We believe in sustainable dining that nourishes both body and soul.',
    primaryColor: '#7C2D12',
    secondaryColor: '#FEF3C7',
    accentColor: '#C2410C',
    fontHeading: 'DM Sans',
    fontBody: 'Inter',
    brandVoice: 'Warm & Caring, Casual & Friendly. Uses food metaphors. Passionate about ingredients and craftsmanship.',
    toneKeywords: ['Warm & Caring', 'Casual & Friendly'],
    channels: ['website', 'chatbot', 'social', 'email'],
    products: [
      { name: 'Seasonal Tasting Menu', description: 'A curated 5-course experience featuring the finest local produce', price: 85, currency: 'USD', category: 'Dining' },
      { name: 'Weekend Brunch', description: 'Leisurely brunch with artisan pastries, fresh juices, and creative egg dishes', price: 35, currency: 'USD', category: 'Dining' },
      { name: 'Chef\'s Table Experience', description: 'An intimate dining experience at the chef\'s table with wine pairing', price: 150, currency: 'USD', category: 'Experience' },
    ],
    chatbotPersona: 'A friendly host who knows every dish on the menu and loves making recommendations',
  },
  {
    id: 'fashion',
    category: 'Fashion/Clothing',
    emoji: '👗',
    name: 'ATELIER',
    description: 'A modern, sustainable fashion brand with minimalist luxury',
    industry: 'Fashion / Clothing',
    tagline: 'Wear the change',
    brandDescription: 'A sustainable fashion label creating timeless pieces from ethically sourced materials. We design for the conscious consumer who values quality over quantity.',
    primaryColor: '#1C1917',
    secondaryColor: '#FAFAF9',
    accentColor: '#A16207',
    fontHeading: 'Space Grotesk',
    fontBody: 'Inter',
    brandVoice: 'Minimalist & Clean, Luxurious & Premium. Short, impactful sentences. Values sustainability and craftsmanship.',
    toneKeywords: ['Minimalist & Clean', 'Luxurious & Premium'],
    channels: ['website', 'ecommerce', 'social', 'email'],
    products: [
      { name: 'The Essential Blazer', description: 'Tailored from organic cotton, a versatile piece for any occasion', price: 280, currency: 'USD', category: 'Outerwear' },
      { name: 'Silk Midi Skirt', description: 'Flowing silhouette in naturally dyed silk, elegance redefined', price: 195, currency: 'USD', category: 'Bottoms' },
      { name: 'Recycled Cashmere Sweater', description: 'Luxuriously soft cashmere crafted from recycled fibers', price: 245, currency: 'USD', category: 'Knitwear' },
    ],
    chatbotPersona: 'A personal stylist who understands sustainable fashion and helps customers find their perfect look',
  },
  {
    id: 'tech',
    category: 'Tech/SaaS',
    emoji: '💻',
    name: 'Nexus',
    description: 'A modern SaaS platform with deep tech branding',
    industry: 'Technology / SaaS',
    tagline: 'Build faster, ship smarter',
    brandDescription: 'A developer-first platform that streamlines workflows and accelerates product delivery. We make complex things simple so teams can focus on what matters.',
    primaryColor: '#1E1B4B',
    secondaryColor: '#EEF2FF',
    accentColor: '#6366F1',
    fontHeading: 'Geist',
    fontBody: 'Inter',
    brandVoice: 'Technical & Expert, Bold & Confident. Concise, no jargon. Speaks developer language.',
    toneKeywords: ['Technical & Expert', 'Bold & Confident'],
    channels: ['website', 'chatbot', 'email', 'push'],
    products: [
      { name: 'Starter Plan', description: 'Everything you need to get started. 5 projects, 10K API calls/month', price: 29, currency: 'USD', category: 'Plans' },
      { name: 'Pro Plan', description: 'For growing teams. Unlimited projects, 100K API calls, priority support', price: 99, currency: 'USD', category: 'Plans' },
      { name: 'Enterprise', description: 'Custom deployment, dedicated support, SSO, and SLA guarantees', price: 499, currency: 'USD', category: 'Plans' },
    ],
    chatbotPersona: 'A technical support agent who can debug issues, explain APIs, and guide developers',
  },
  {
    id: 'fitness',
    category: 'Fitness/Wellness',
    emoji: '🏋️',
    name: 'CORE',
    description: 'An energetic fitness brand with high-impact styling',
    industry: 'Fitness / Wellness',
    tagline: 'Stronger every day',
    brandDescription: 'A holistic fitness community that combines cutting-edge training with mindful wellness practices. We believe fitness is not just physical — it\'s a lifestyle.',
    primaryColor: '#0A0A0A',
    secondaryColor: '#F0FDF4',
    accentColor: '#22C55E',
    fontHeading: 'Outfit',
    fontBody: 'DM Sans',
    brandVoice: 'Bold & Confident, Warm & Caring. Motivational but authentic. Uses action verbs.',
    toneKeywords: ['Bold & Confident', 'Warm & Caring'],
    channels: ['website', 'chatbot', 'social', 'push', 'email'],
    products: [
      { name: 'Monthly Membership', description: 'Unlimited access to all classes, equipment, and wellness amenities', price: 79, currency: 'USD', category: 'Membership' },
      { name: 'Personal Training (10 Sessions)', description: 'One-on-one sessions with a certified trainer tailored to your goals', price: 650, currency: 'USD', category: 'Training' },
      { name: 'Wellness Retreat Weekend', description: '3-day immersive retreat with yoga, meditation, and nutrition workshops', price: 450, currency: 'USD', category: 'Events' },
    ],
    chatbotPersona: 'An encouraging fitness coach who helps members find the right classes and answers wellness questions',
  },
  {
    id: 'education',
    category: 'Education/Courses',
    emoji: '📚',
    name: 'Lumina Academy',
    description: 'An online learning platform with modern, engaging branding',
    industry: 'Education / Online Learning',
    tagline: 'Learn without limits',
    brandDescription: 'An innovative online learning platform offering expert-led courses that transform careers. Interactive, practical, and designed for the modern learner.',
    primaryColor: '#14532D',
    secondaryColor: '#FFFBEB',
    accentColor: '#D97706',
    fontHeading: 'Plus Jakarta Sans',
    fontBody: 'Inter',
    brandVoice: 'Professional, Warm & Caring. Encouraging and clear. Makes complex topics accessible.',
    toneKeywords: ['Professional', 'Warm & Caring'],
    channels: ['website', 'chatbot', 'email', 'social'],
    products: [
      { name: 'Web Development Bootcamp', description: 'From zero to job-ready in 12 weeks. HTML, CSS, React, Node.js', price: 499, currency: 'USD', category: 'Courses' },
      { name: 'Data Science Masterclass', description: 'Master Python, ML, and data visualization with real-world projects', price: 399, currency: 'USD', category: 'Courses' },
      { name: 'Annual Pro Membership', description: 'Access all 200+ courses, certificates, and mentorship sessions', price: 199, currency: 'USD', category: 'Membership' },
    ],
    chatbotPersona: 'A knowledgeable academic advisor who helps students choose the right learning path',
  },
  {
    id: 'realestate',
    category: 'Real Estate',
    emoji: '🏠',
    name: 'Haven Properties',
    description: 'A premium real estate agency with trust & luxury styling',
    industry: 'Real Estate',
    tagline: 'Find your forever home',
    brandDescription: 'A premium real estate agency specializing in residential properties. We combine market expertise with personalized service to help clients find their perfect home.',
    primaryColor: '#0F172A',
    secondaryColor: '#FEF9EF',
    accentColor: '#B45309',
    fontHeading: 'Manrope',
    fontBody: 'Inter',
    brandVoice: 'Luxurious & Premium, Professional. Sophisticated yet approachable. Builds trust and authority.',
    toneKeywords: ['Luxurious & Premium', 'Professional'],
    channels: ['website', 'chatbot', 'email', 'crm'],
    products: [
      { name: 'Home Buying Consultation', description: 'Complimentary session to understand your needs and explore options', price: 0, currency: 'USD', category: 'Services' },
      { name: 'Property Valuation', description: 'Professional market analysis and property valuation report', price: 250, currency: 'USD', category: 'Services' },
      { name: 'Premium Listing Package', description: 'Professional photography, virtual tour, and targeted marketing', price: 1500, currency: 'USD', category: 'Packages' },
    ],
    chatbotPersona: 'A knowledgeable real estate agent who can answer property questions and schedule viewings',
  },
  {
    id: 'beauty',
    category: 'Beauty/Salon',
    emoji: '✂️',
    name: 'Glow Studio',
    description: 'A chic beauty brand with rose pink & deep plum tones',
    industry: 'Beauty / Salon',
    tagline: 'Your glow, your story',
    brandDescription: 'A modern beauty studio offering personalized treatments that celebrate your unique beauty. From hair styling to skincare, we create experiences, not just appointments.',
    primaryColor: '#581C87',
    secondaryColor: '#FFF1F2',
    accentColor: '#DB2777',
    fontHeading: 'Sora',
    fontBody: 'DM Sans',
    brandVoice: 'Playful & Fun, Warm & Caring. Empowering and inclusive. Celebrates individuality.',
    toneKeywords: ['Playful & Fun', 'Warm & Caring'],
    channels: ['website', 'chatbot', 'social', 'email'],
    products: [
      { name: 'Signature Haircut & Style', description: 'Consultation, precision cut, and professional styling', price: 85, currency: 'USD', category: 'Hair' },
      { name: 'Glow Facial Treatment', description: 'Customized facial with organic products for radiant skin', price: 120, currency: 'USD', category: 'Skin' },
      { name: 'Bridal Package', description: 'Complete hair, makeup, and skincare prep for your special day', price: 350, currency: 'USD', category: 'Packages' },
    ],
    chatbotPersona: 'A friendly beauty consultant who helps clients book appointments and recommends treatments',
  },
  {
    id: 'music',
    category: 'Music/Entertainment',
    emoji: '🎵',
    name: 'Soundwave',
    description: 'A vibrant music brand with electric purple & magenta',
    industry: 'Music / Entertainment',
    tagline: 'Feel the frequency',
    brandDescription: 'An independent music label and events company bringing fresh sounds to life. We discover, produce, and share music that moves people.',
    primaryColor: '#0A0A0A',
    secondaryColor: '#FAF5FF',
    accentColor: '#A855F7',
    fontHeading: 'Space Grotesk',
    fontBody: 'Inter',
    brandVoice: 'Bold & Confident, Playful & Fun. Energetic and creative. Speaks the language of music culture.',
    toneKeywords: ['Bold & Confident', 'Playful & Fun'],
    channels: ['website', 'social', 'email', 'push'],
    products: [
      { name: 'Festival Pass', description: 'All-access pass to our 3-day annual music festival', price: 199, currency: 'USD', category: 'Events' },
      { name: 'Studio Session (4 Hours)', description: 'Professional recording studio time with engineer support', price: 400, currency: 'USD', category: 'Studio' },
      { name: 'Artist Development Package', description: 'Complete artist branding, production, and distribution support', price: 2500, currency: 'USD', category: 'Services' },
    ],
    chatbotPersona: 'A music-savvy assistant who knows upcoming events, artist rosters, and studio availability',
  },
  {
    id: 'retail',
    category: 'General Retail',
    emoji: '🛒',
    name: 'Curate',
    description: 'A curated marketplace with rich teal & coral styling',
    industry: 'General Retail / Marketplace',
    tagline: 'Curated for you',
    brandDescription: 'A thoughtfully curated online marketplace featuring handpicked products from independent makers. Every item tells a story and meets our quality standards.',
    primaryColor: '#134E4A',
    secondaryColor: '#FFF7ED',
    accentColor: '#F97316',
    fontHeading: 'Plus Jakarta Sans',
    fontBody: 'DM Sans',
    brandVoice: 'Casual & Friendly, Warm & Caring. Storytelling focused. Highlights craftsmanship and makers.',
    toneKeywords: ['Casual & Friendly', 'Warm & Caring'],
    channels: ['website', 'ecommerce', 'social', 'email', 'chatbot'],
    products: [
      { name: 'Artisan Candle Set', description: 'Hand-poured soy candles in three seasonal scents', price: 45, currency: 'USD', category: 'Home' },
      { name: 'Leather Journal', description: 'Handcrafted genuine leather journal with 200 recycled pages', price: 38, currency: 'USD', category: 'Stationery' },
      { name: 'Ceramic Mug Collection', description: 'Set of 4 handmade ceramic mugs in earth tones', price: 65, currency: 'USD', category: 'Kitchen' },
    ],
    chatbotPersona: 'A helpful shopping assistant who knows every product\'s story and helps find the perfect gift',
  },
  {
    id: 'healthcare',
    category: 'Healthcare',
    emoji: '🏥',
    name: 'Vitalis Health',
    description: 'A modern healthcare clinic with deep teal & mint tones',
    industry: 'Healthcare / Medical',
    tagline: 'Health centered around you',
    brandDescription: 'A modern healthcare clinic offering comprehensive medical services with a patient-first approach. We combine advanced technology with compassionate care.',
    primaryColor: '#0F4C5C',
    secondaryColor: '#F0FDFA',
    accentColor: '#0D9488',
    fontHeading: 'Manrope',
    fontBody: 'Inter',
    brandVoice: 'Professional, Warm & Caring. Clear and reassuring. Avoids medical jargon. Empathetic.',
    toneKeywords: ['Professional', 'Warm & Caring'],
    channels: ['website', 'chatbot', 'email', 'crm'],
    products: [
      { name: 'General Check-up', description: 'Comprehensive health assessment with lab work and consultation', price: 250, currency: 'USD', category: 'Services' },
      { name: 'Telemedicine Consultation', description: 'Virtual doctor visit from the comfort of your home', price: 75, currency: 'USD', category: 'Services' },
      { name: 'Annual Wellness Plan', description: 'Year-round health monitoring with quarterly check-ups and priority access', price: 1200, currency: 'USD', category: 'Plans' },
    ],
    chatbotPersona: 'A caring medical receptionist who helps with appointments, general health questions, and clinic info',
  },
];

export function getTemplate(id: string): StarterTemplate | undefined {
  return STARTER_TEMPLATES.find(t => t.id === id);
}

export function templateToBrandData(template: StarterTemplate): BrandData {
  return {
    name: template.name,
    tagline: template.tagline,
    industry: template.industry,
    description: template.brandDescription,
    templateId: template.id,
    primaryColor: template.primaryColor,
    secondaryColor: template.secondaryColor,
    accentColor: template.accentColor,
    fontHeading: template.fontHeading,
    fontBody: template.fontBody,
    products: template.products,
    brandVoice: template.brandVoice,
    toneKeywords: template.toneKeywords,
    channels: template.channels,
    status: 'draft',
  };
}
